"""Tipos de evento do fluxo (piloto §24, docs/04 §4.6).

O conjunto deve permanecer estável durante a coleta definitiva.
"""

from enum import StrEnum


class EventType(StrEnum):
    ORDER_CREATED = "ORDER_CREATED"
    TASK_CREATED = "TASK_CREATED"
    STOCK_RESERVATION_REQUESTED = "STOCK_RESERVATION_REQUESTED"
    STOCK_RESERVATION_SUCCEEDED = "STOCK_RESERVATION_SUCCEEDED"
    STOCK_RESERVATION_FAILED = "STOCK_RESERVATION_FAILED"
    INVENTORY_TIMEOUT = "INVENTORY_TIMEOUT"
    TRANSIENT_ERROR = "TRANSIENT_ERROR"
    WAIT_SCHEDULED = "WAIT_SCHEDULED"
    WAIT_FINISHED = "WAIT_FINISHED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    FALLBACK_SCHEDULED = "FALLBACK_SCHEDULED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_ABORTED = "TASK_ABORTED"
    MESSAGE_DEAD_LETTERED = "MESSAGE_DEAD_LETTERED"
